# ⁡⁣⁢⁣imagem base⁡
FROM nginx

# ⁡⁣⁢⁣copiar os arquivos da minha máquina para o container⁡⁣⁢⁣ (documentação do próprio nginx)
# https://hub.docker.com/_/nginx⁡⁡
COPY index.html /usr/share/nginx/html
COPY teste.html /usr/share/nginx/html
